<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <RootNamespace>MVoxelEngine1.Application</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Games\Default\Assets\Images\**" />
    <Compile Remove="Games\Default\Assets\Music\**" />
    <Compile Remove="Games\Default\Assets\Sounds\**" />
    <EmbeddedResource Remove="Games\Default\Assets\Images\**" />
    <EmbeddedResource Remove="Games\Default\Assets\Music\**" />
    <EmbeddedResource Remove="Games\Default\Assets\Sounds\**" />
    <None Remove="Games\Default\Assets\Images\**" />
    <None Remove="Games\Default\Assets\Music\**" />
    <None Remove="Games\Default\Assets\Sounds\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\MVoxelEngine1.Infrastructure\MVoxelEngine1.Infrastructure.csproj" />
	  <ProjectReference Include="..\MVoxelEngine1.WorldGeneration\MVoxelEngine1.WorldGeneration.csproj" />
	<ProjectReference Include="..\MVoxelEngine1.Graphics\MVoxelEngine1.Graphics.csproj" />
	<ProjectReference Include="..\MVoxelEngine1.Tools\MVoxelEngine1.Tools.csproj" />
  </ItemGroup>

</Project>
