<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MVoxelEngine1.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <AssemblyMetadata Include="RepositoryRoot" Value="$(MSBuildProjectDirectory)/.." />
  </ItemGroup>

  <Target Name="ResolveApplicationTestPath" BeforeTargets="GetAssemblyAttributes">
    <MSBuild Projects="../MVoxelEngine1.Application/MVoxelEngine1.Application.csproj"
             Targets="GetTargetPath" Properties="Configuration=$(Configuration)">
      <Output TaskParameter="TargetOutputs" ItemName="ApplicationTestTarget" />
    </MSBuild>
    <ItemGroup>
      <AssemblyMetadata Include="ApplicationTargetPath" Value="@(ApplicationTestTarget)" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MVoxelEngine1.Application\MVoxelEngine1.Application.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\MVoxelEngine1.Graphics\MVoxelEngine1.Graphics.csproj" />
    <ProjectReference Include="..\MVoxelEngine1.Infrastructure\MVoxelEngine1.Infrastructure.csproj" />
    <ProjectReference Include="..\MVoxelEngine1.WorldGeneration\MVoxelEngine1.WorldGeneration.csproj" />
  </ItemGroup>

</Project>
